spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_iot
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNaming.Strategy
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false